import random as r
x=1

tipos = ["Climatización Módulo",
"Condensador de Aire Acondicionado",
"Ensamblaje de Ventilador de Condensador de Aire Acondicionado",
"Filtro de Aire de Cabina",
"Manguera de Calefactor",
"Módulo de Control / Resistencia de Motor de Ventilador",
"Sensor de Temperatura de Aire Ambiente",
"Carrocería y Ensamblaje de Lámpara",
"Actuador de Cerradura de Puerta",
"Amortiguador de Soporte",
"Combustible y Aire",
"Bomba de Combustible",
"Colador de Bomba de Combustible",
"Ensamblaje de Bomba de Combustible y Carcasa",
"Filtro de Aire",
"Filtro de Combustible",
"Inyector de Combustible",
"Sensor de Posición de Acelerador (TPS)",
"Soporte Colgante de Combustible",
"Válvula de Control de Aire de Ralentí (IAC)",
"Correa de Transmisión",
"Correa",
"Polea de Tensor",
"Polea Loca",
"Tensor de Correa",
"Amortiguador de dirección",
"Bomba de Dirección Hidráulica",
"Brazo Auxiliar",
"Brazo Pitman",
"Buje de Biela de Dirección",
"Buje de Cremallera",
"Centro / Biela de Arrastre",
"Cremallera",
"Fuelle de Amortiguador de Dirección",
"Juego de Revisión de Caja de Engranaje de Dirección",
"Manga de Ajuste de Rótula de Dirección",
"Manguera de Presión de Dirección Hidráulica",
"Manguera de Retorno de Dirección Hidráulica",
"Rótula de Dirección",
"Sensor de Posición de Volante",
"Eléctrico",
"Alambre de Luz de Cenicero",
"Sensor de Velocidad",
"Bombilla de Faro",
"Bombilla de Lámpara de Cola",
"Bombilla de Lámpara de Estacionamiento",
"Bombilla de Lámpara de Manejo / Neblina",
"Cazonete	Bombilla de Lámpara de Placa de Matricula",
"Bombilla de Lámpara de Retroceso / Marcha Atrás",
"Bombilla de Lámpara Direccional",
"Bombilla de Luz de Dial de Radio",
"Bombilla de Luz de Encendido",
"Bombilla de Luz de Freno - Alto Soporte",
"Bombilla de Luz de Guantera",
"Bombilla de Luz Marcadora Lateral",
"Casquillo de Faro",
"Paso / Bombilla de Luz de Cortesía",
"Conector de Sensor de Velocidad de Rueda de ABS (Sistema de Freno Anti-Bloqueo)",
"Interruptor / Enviador de Presión de Aceite",
"Interruptor / Panel de Control de Aire Acondicionado y Calefactor",
"Interruptor de Arranque/Encendido",
"Interruptor de Freno de Estacionamiento",
"Interruptor de Luz de Freno",
"Interruptor de Presión de Refrigerante",
"Interruptor de Ventana Eléctrica",
"Relé de Motor de Arranque de Encendido",
"Sensor de Rango / Interruptor de Seguridad Neutral",
"Bobina de Encendido",
"Bujía / Bobina de Encendido Bota",
"Cable de Bujía",
"Distribuidor",
"Rotor de Distribuidor",
"Sello de Tubo de Bujía",
"Sensor de Posición de Árbol de Levas",
"Sensor de Posición de Cigüeñal",
"Tapa de distribuidor",
"Emisiones",
"Abrazadera "'Clamp'"",
"Abrazadera de Escape",
"Cinturón de Silenciador",
"Convertidor Catalítico",
"Empaque / Sello de Brida de Tubo",
"Empaque de Múltiple de Escape",
"Perno / Resorte",
"Punta de Tubo",
"Sensor de Detonación",
"Sensor de Flujo de Aire (MAF)",
"Sensor de Oxígeno (O2)",
"Silenciador",
"Soporte Colgante / Aislador",
"Soporte de Escape",
"Tubo / Resonador",
"Válvula / Solenoide de Purga de Bote de Vapor",
"Válvula / Solenoide de Ventilación de Bote de Vapor",
"Válvula de Ventilación Positiva del Cárter (PCV)",
"Válvula EGR (Recirculación de Gases de Escape)",
"aza de Rueda",
"Anillo de Retención de Cojinete de Rueda",
"Cable de Freno de Estacionamiento",
"Cilindro de Freno",
"Cilindro Maestro",
"Cojinete de Rueda",
"Cojinete de Rueda y Maza",
"Juego de Hardware de Freno de Disco",
"Juego de Reparación de Autoajuste de Freno de Tambor",
"Juego de Retención de Zapata de Freno",
"Manguera de Freno",
"Maza de Rueda",
"Mordaza",
"Pastilla de Freno",
"Pista de Cojinete y Conductor de Sello",
"Rotor",
"Sello de Rueda",
"Sensor de Desgaste de Pastilla de Freno",
"Sensor de Nivel de Fluido de Freno",
"Sensor de Velocidad de Rueda de ABS (Sistema de Freno Anti-Bloqueo)",
"Tambor",
"Zapata de Freno",
"Zapata de Freno de Estacionamiento",
"Ensamblaje de Regulador de Ventana y Motor",
"Motor de Ventana",
"Pedal de Acelerador",
"Regulador de Ventana",
"Motor",
"Ajuste de Tensor de Correa de Distribución",
"Buje de Soporte de Motor",
"Correa de Distribución",
"Correa de Eje de Equilibrio",
"Empaque de Bomba de Aceite",
"Empaque de Cacerola de Aceite",
"Empaque de Cojinete de Cigüeñal",
"Empaque de Culata",
"Empaque de Múltiple de Admisión",
"Empaque de Plenum de Admisión",
"Empaque de Tapa de Válvulas",
"Enfriador de Aceite",
"Filtro de Aceite",
"Juego de Empaque de Múltiples de Admisión y Escape",
"Juego de Empaques de Culata",
"Ojal de Tapa de Válvulas",
"Polea Loca de Distribución",
"Sello de Árbol de Levas",
"Sello de Cigüeñal",
"Solenoide / Actuador de Distribución de Válvula Variable (VVT)",
"Soporte de Motor",
"Soporte de Torsión",
"Tapón de Culata",
"Tensor de Correa de Distribución",
"Bomba de Agua",
"Carcasa de Termostato / Salida de Agua",
"Depósito de Refrigerante",
"Embrague de Ventilador de Radiador",
"Ensamblaje de Ventilador de Radiador",
"Enviador / Sensor de Temperatura",
"Motor de Ventilador de Radiador",
"Termostato",
"Termostato / Sello de Carcasa de Termostato / Salida de Agua",
"Aislador de Muelle de Hojas",
"Amortiguador / Amortiguador (Puntal)",
"Amortiguador / Amortiguador (Puntal) y Resorte Espiral Ensamblaje",
"Amortiguador / Cojinete de Amortiguador (Puntal)",
"Amortiguador / Soporte de Amortiguador (Puntal)",
"Asiento / Aislador de Resorte Espiral",
"Barra de Guía",
"Brazo de Control",
"Buje de Ángulo de Avance del Pivote / Ángulo de Caída de Alineación",
"Buje de Barra de Guía",
"Buje de Barra Estabilizadora",
"Buje de Biela de Retención",
"Buje de Brazo de Control",
"Buje de Eje",
"Enlace de Barra Estabilizadora",
"Juego de Eje de Brazo de Control",
"Perno de Alineación / Placa de Ángulo de Caída",
"Resorte Espiral",
"Rótula",
"Soporte de Barra de Torsión",
"Tope",
"Transmisión-Automática",
"Anillo de Reten",
"Filtro",
"Junta Tórica y Sellos",
"Sello de Eje de Convertidor de Torsión",
"Sello de Eje de Salida",
"Soporte de Transmisión",
"Cable de Embrague",
"Cilindro Esclavo de Embrague",
"Cilindro Maestro de Embrague",
"Juego de Embrague",
"Soporte de Transmisión",
"Volante de Inercia",
"Tren de Transmisión",
"Bota de Junta Homocinética",
"Cojinete / Pista de Piñón de Diferencial",
"Cojinete / Pista de Portador de Portador de Diferencial",
"Cojinete de Eje de Salida de Caja de Transferencia",
"Eje de Junta Homocinética",
"Soporte / Cojinete Central de Flecha Cardán",
"Unión Universal"
]





while True:
    print("{"'"idProd": '+str(x)+',\n"nomProd":"'+tipos[x]+'",\n"valorProd":'+str(r.randint(3000,50000))+',\n"descProd": "Texto descriptivo",\n"imgSrc":"img/api/'+str(x)+'.png"}, ')
    if x>25:
      print("{"'"idProd": '+str(x)+',\n"nomProd":"'+tipos[x]+'",\n"valorProd":'+str(r.randint(3000,50000))+',\n"descProd": "Texto descriptivo",\n"imgSrc":"img/api/2.png"}, ')
     
    x=x+1
    if x==199:
     break
