# Generated by Django 4.1.2 on 2023-07-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProd', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('marca_producto', models.CharField(max_length=200)),
                ('upc_producto', models.BigIntegerField(default=0)),
                ('cantidad_paquete', models.CharField(default=0, max_length=50)),
                ('valor_compra', models.IntegerField(default=0)),
                ('valor_venta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriaProd',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCatProd', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
                ('id_genero', models.ForeignKey(db_column='idGenero', default=3, on_delete=django.db.models.deletion.CASCADE, to='clientes.genero')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCatProd', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('id_subCat', models.ForeignKey(db_column='SubCategoriaProd.idCatProd', on_delete=django.db.models.deletion.CASCADE, to='clientes.subcategoriaprod')),
            ],
        ),
    ]
