# Generated by Django 4.1.2 on 2023-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_genero',
        ),
    ]
