# Generated by Django 4.1.2 on 2023-07-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.AutoField(db_column='num_boleta', primary_key=True, serialize=False)),
                ('fecha_boleta', models.DateField()),
                ('monto_boleta', models.IntegerField(default=0)),
                ('activa', models.IntegerField()),
                ('num_cliente', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
